package com.focamacho.mysticaladaptations.config;

import java.io.File;

import com.focamacho.mysticaladaptations.Main;
import com.focamacho.mysticaladaptations.util.Reference;

import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

public class ModConfig 
{
	public static Configuration config;
	public static ModConfig instance;
	
	public static int INFERIUM_DURABILITY;
	public static int PRUDENTIUM_DURABILITY;
	public static int INTERMEDIUM_DURABILITY;
	public static int SUPERIUM_DURABILITY;
	public static int SUPREMIUM_DURABILITY;
	public static int INSANIUM_DURABILITY;
	
	public static boolean MOB_SEED_DROP;
	public static boolean EXTRACTOR_LOWER_TIER;
	public static boolean EXTRACTOR_ANY_TIER;
	public static boolean REMOVE_SEED_RECIPES;
	
	public static boolean NETHERSTAR_BLOCK;
	public static boolean SILICON_BLOCK;
	
	public static String abyssalnite_seeds;
	public static String adamantine_seeds;
	public static String aluminum_brass_seeds;
	public static String aluminum_seeds;
	public static String alumite_seeds;
	public static String amber_seeds;
	public static String apatite_seeds;
	public static String aquamarine_seeds;
	public static String aquarium_seeds;
	public static String ardite_seeds;
	public static String basalt_seeds;
	public static String black_quartz_seeds;
	public static String blue_topaz_seeds;
	public static String boron_seeds;
	public static String brass_seeds;
	public static String bronze_seeds;
	public static String certus_quartz_seeds;
	public static String chimerite_seeds;
	public static String chrome_seeds;
	public static String coal_seeds;
	public static String cobalt_seeds;
	public static String cold_iron_seeds;
	public static String compressed_iron_seeds;
	public static String conductive_iron_seeds;
	public static String constantan_seeds;
	public static String copper_seeds;
	public static String coralium_seeds;
	public static String dark_gem_seeds;
	public static String dark_steel_seeds;
	public static String dawnstone_seeds;
	public static String desh_seeds;
	public static String diamond_seeds;
	public static String dilithium_seeds;
	public static String dirt_seeds;
	public static String draconium_seeds;
	public static String dreadium_seeds;
	public static String dye_seeds;
	public static String electrical_steel_seeds;
	public static String electrotine_seeds;
	public static String electrum_seeds;
	public static String elementium_seeds;
	public static String emerald_seeds;
	public static String end_seeds;
	public static String end_steel_seeds;
	public static String ender_amethyst_seeds;
	public static String ender_biotite_seeds;
	public static String enderium_seeds;
	public static String energetic_alloy_seeds;
	public static String experience_seeds;
	public static String fiery_ingot_seeds;
	public static String fire_seeds;
	public static String fluix_seeds;
	public static String fluxed_electrum_seeds;
	public static String glowstone_ingot_seeds;
	public static String glowstone_seeds;
	public static String gold_seeds;
	public static String grains_of_infinity_seeds;
	public static String graphite_seeds;
	public static String hop_graphite_seeds;
	public static String ice_seeds;
	public static String invar_seeds;
	public static String iridium_ore_seeds;
	public static String iridium_seeds;
	public static String iron_seeds;
	public static String ironwood_seeds;
	public static String jade_seeds;
	public static String knightmetal_seeds;
	public static String knightslime_seeds;
	public static String lapis_lazuli_seeds;
	public static String lead_seeds;
	public static String limestone_seeds;
	public static String lithium_seeds;
	public static String lumium_seeds;
	public static String magnesium_seeds;
	public static String malachite_seeds;
	public static String manasteel_seeds;
	public static String manyullyn_seeds;
	public static String marble_seeds;
	public static String menril_seeds;
	public static String meteoric_iron_seeds;
	public static String mithril_seeds;
	public static String moonstone_seeds;
	public static String mystical_flower_seeds;
	public static String nature_seeds;
	public static String nether_quartz_seeds;
	public static String nether_seeds;
	public static String nickel_seeds;
	public static String obsidian_seeds;
	public static String octine_seeds;
	public static String osmium_seeds;
	public static String peridot_seeds;
	public static String platinum_seeds;
	public static String pulsating_iron_seeds;
	public static String quartz_enriched_iron_seeds;
	public static String quicksilver_seeds;
	public static String redstone_alloy_seeds;
	public static String redstone_seeds;
	public static String refined_obsidian_seeds;
	public static String rock_crystal_seeds;
	public static String rubber_seeds;
	public static String ruby_seeds;
	public static String saltpeter_seeds;
	public static String sapphire_seeds;
	public static String signalum_seeds;
	public static String silicon_seeds;
	public static String silver_seeds;
	public static String sky_stone_seeds;
	public static String slate_seeds;
	public static String slimy_bone_seeds;
	public static String soularium_seeds;
	public static String star_steel_seeds;
	public static String starmetal_seeds;
	public static String steel_seeds;
	public static String steeleaf_seeds;
	public static String stone_seeds;
	public static String sulfur_seeds;
	public static String sunstone_seeds;
	public static String syrmorite_seeds;
	public static String tanzanite_seeds;
	public static String terrasteel_seeds;
	public static String thaumium_seeds;
	public static String thorium_seeds;
	public static String tin_seeds;
	public static String titanium_seeds;
	public static String topaz_seeds;
	public static String tritanium_seeds;
	public static String tungsten_seeds;
	public static String uranium_238_seeds;
	public static String uranium_seeds;
	public static String valonite_seeds;
	public static String vibrant_alloy_seeds;
	public static String vinteum_seeds;
	public static String void_metal_seeds;
	public static String water_seeds;
	public static String wood_seeds;
	public static String yellorium_seeds;
	public static String zinc_seeds;
	public static String awakened_draconium_seeds;
	public static String dragon_egg_seeds;
	public static String nether_star_seeds;
	public static String neutronium_seeds;
	public static String basalz_seeds;
	public static String blaze_seeds;
	public static String blitz_seeds;
	public static String blizz_seeds;
	public static String chicken_seeds;
	public static String cow_seeds;
	public static String creeper_seeds;
	public static String enderman_seeds;
	public static String ghast_seeds;
	public static String guardian_seeds;
	public static String pig_seeds;
	public static String rabbit_seeds;
	public static String sheep_seeds;
	public static String skeleton_seeds;
	public static String slime_seeds;
	public static String spider_seeds;
	public static String wither_skeleton_seeds;
	public static String zombie_seeds;
	
	@SubscribeEvent
    public void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent eventArgs) {
        if(eventArgs.getModID().equals(Reference.MOD_ID)) {
            ModConfig.syncConfig();
        }
    }
	
	public static void init(File file) {
        config = new Configuration(file);
        syncConfig();
	}
	
	public static void syncConfig() {
	
		String category;
		
		category = "Seed Extractor Durability";
		config.addCustomCategoryComment(category, "Set the durability of the Seed Extractors");
		INFERIUM_DURABILITY = config.getInt("INFERIUM_DURABILITY", category, 15, 1, 2147483647, "Inferium Seed Extractor Durability.");
		PRUDENTIUM_DURABILITY = config.getInt("PRUDENTIUM_DURABILITY", category, 15, 1, 2147483647, "Prudentium Seed Extractor Durability.");
		INTERMEDIUM_DURABILITY = config.getInt("INTERMEDIUM_DURABILITY", category, 15, 1, 2147483647, "Intermedium Seed Extractor Durability.");
		SUPERIUM_DURABILITY = config.getInt("SUPERIUM_DURABILITY", category, 15, 1, 2147483647, "Superium Seed Extractor Durability.");
		SUPREMIUM_DURABILITY = config.getInt("SUPREMIUM_DURABILITY", category, 15, 1, 2147483647, "Supremium Seed Extractor Durability.");
		INSANIUM_DURABILITY = config.getInt("INSANIUM_DURABILITY", category, 15, 1, 2147483647, "Supremium Seed Extractor Durability. (Only if Mystical Agradditions is loaded)");
		
		category = "Additional Mechanics";
		config.addCustomCategoryComment(category, "Some additional mechanics available");
		MOB_SEED_DROP = config.getBoolean("MOB_SEED_DROP", category, true, "Kill a mob using a Seed Extractor to get its seed.");
		EXTRACTOR_LOWER_TIER = config.getBoolean("EXTRACTOR_LOWER_TIER", category, true, "Seed Extractor of larger tiers can pick lower tier seeds.");
		EXTRACTOR_ANY_TIER = config.getBoolean("EXTRACTOR_ANY_TIER", category, false, "Seed extractors can collect any seed, regardless of the tier.");
		REMOVE_SEED_RECIPES = config.getBoolean("REMOVE_SEED_RECIPES", category, true, "Remove all default crafting table seed recipes");
	
		category = "Blocks(Enable/Disable)";
		config.addCustomCategoryComment(category, "Enable/Disable Blocks");
		NETHERSTAR_BLOCK = config.get(category, "NETHERSTAR_BLOCK", true).getBoolean();
		SILICON_BLOCK = config.get(category, "SILICON_BLOCK", true).getBoolean();

		category = "Seeds drops";
		config.addCustomCategoryComment(category, "Set which block or entity drops a seed when right-clicked/killed using a Seed Extractor");
	    abyssalnite_seeds = config.get(category, "abyssalnite_seeds", "ore:blockAbyssalnite").getString();
	    adamantine_seeds = config.get(category, "adamantine_seeds", "ore:blockAdamantine").getString();
	    aluminum_brass_seeds = config.get(category, "aluminum_brass_seeds", "ore:blockAlubrass").getString();
	    aluminum_seeds = config.get(category, "aluminum_seeds", "ore:blockAluminum").getString();
	    alumite_seeds = config.get(category, "alumite_seeds", "ore:blockAlumite").getString();
	    amber_seeds = config.get(category, "amber_seeds", "biomesoplenty:gem_block:7").getString();
	    apatite_seeds = config.get(category, "apatite_seeds", "ore:blockApatite").getString();
	    aquamarine_seeds = config.get(category, "aquamarine_seeds", "astralsorcery:blockcustomsandore").getString();
	    aquarium_seeds = config.get(category, "aquarium_seeds", "ore:blockAquarium").getString();
	    ardite_seeds = config.get(category, "ardite_seeds", "ore:blockArdite").getString();
	    basalt_seeds = config.get(category, "basalt_seeds", "ore:stoneBasalt").getString();
	    black_quartz_seeds = config.get(category, "black_quartz_seeds", "ore:blockQuartzBlack").getString();
	    blue_topaz_seeds = config.get(category, "blue_topaz_seeds", "ore:blockBlueTopaz").getString();
	    boron_seeds = config.get(category, "boron_seeds", "ore:blockBoron").getString();
	    brass_seeds = config.get(category, "brass_seeds", "ore:blockBrass").getString();
	    bronze_seeds = config.get(category, "bronze_seeds", "ore:blockBronze").getString();
	    certus_quartz_seeds = config.get(category, "certus_quartz_seeds", "appliedenergistics2:quartz_block").getString();
	    chimerite_seeds = config.get(category, "chimerite_seeds", "ore:blockChimerite").getString();
	    chrome_seeds = config.get(category, "chrome_seeds", "ore:blockChrome").getString();
	    coal_seeds = config.get(category, "coal_seeds", "ore:blockCoal").getString();
	    cobalt_seeds = config.get(category, "cobalt_seeds", "ore:blockCobalt").getString();
	    cold_iron_seeds = config.get(category, "cold_iron_seeds", "ore:blockColdiron").getString();
	    compressed_iron_seeds = config.get(category, "compressed_iron_seeds", "ore:blockIronCompressed").getString();
	    conductive_iron_seeds = config.get(category, "conductive_iron_seeds", "ore:blockConductiveIron").getString();
	    constantan_seeds = config.get(category, "constantan_seeds", "ore:blockConstantan").getString();
	    copper_seeds = config.get(category, "copper_seeds", "ore:blockCopper").getString();
	    coralium_seeds = config.get(category, "coralium_seeds", "ore:blockLiquifiedCoralium").getString();
	    dark_gem_seeds = config.get(category, "dark_gem_seeds", "evilcraft:dark_block").getString();
	    dark_steel_seeds = config.get(category, "dark_steel_seeds", "ore:blockDarkSteel").getString();
	    dawnstone_seeds = config.get(category, "dawnstone_seeds", "ore:blockDawnstone").getString();
	    desh_seeds = config.get(category, "desh_seeds", "ore:blockDesh").getString();
	    diamond_seeds = config.get(category, "diamond_seeds", "ore:blockDiamond").getString();
	    dilithium_seeds = config.get(category, "dilithium_seeds", "ore:oreDilithium").getString();
	    dirt_seeds = config.get(category, "dirt_seeds", "ore:dirt").getString();
	    draconium_seeds = config.get(category, "draconium_seeds", "ore:blockDraconium").getString();
	    dreadium_seeds = config.get(category, "dreadium_seeds", "ore:blockDreadium").getString();
	    dye_seeds = config.get(category, "dye_seeds", "minecraft:yellow_flower;minecraft:red_flower;minecraft:red_flower:1;minecraft:red_flower:2;minecraft:red_flower:3;minecraft:red_flower:4;minecraft:red_flower:5;minecraft:red_flower:6;minecraft:red_flower:7;minecraft:red_flower:8").getString();
	    electrical_steel_seeds = config.get(category, "electrical_steel_seeds", "ore:blockElectricalSteel").getString();
	    electrotine_seeds = config.get(category, "electrotine_seeds", "").getString();
	    electrum_seeds = config.get(category, "electrum_seeds", "ore:blockElectrum").getString();
	    elementium_seeds = config.get(category, "elementium_seeds", "botania:storage:2").getString();
	    emerald_seeds = config.get(category, "emerald_seeds", "ore:blockEmerald").getString();
	    end_seeds = config.get(category, "end_seeds", "ore:endstone").getString();
	    end_steel_seeds = config.get(category, "end_steel_seeds", "ore:blockEndSteel").getString();
	    ender_amethyst_seeds = config.get(category, "ender_amethyst_seeds", "biomesoplenty:gem_block").getString();
	    ender_biotite_seeds = config.get(category, "ender_biotite_seeds", "quark:biotite_block").getString();
	    enderium_seeds = config.get(category, "enderium_seeds", "ore:blockEnderium").getString();
	    energetic_alloy_seeds = config.get(category, "energetic_alloy_seeds", "ore:blockEnergeticAlloy").getString();
	    experience_seeds = config.get(category, "experience_seeds", "").getString();
	    fiery_ingot_seeds = config.get(category, "fiery_ingot_seeds", "ore:blockFiery").getString();
	    fire_seeds = config.get(category, "fire_seeds", "minecraft:lava").getString();
	    fluix_seeds = config.get(category, "fluix_seeds", "appliedenergistics2:fluix_block").getString();
	    fluxed_electrum_seeds = config.get(category, "fluxed_electrum_seeds", "ore:blockElectrumFlux").getString();
	    glowstone_ingot_seeds = config.get(category, "glowstone_ingot_seeds", "ore:blockRefinedGlowstone").getString();
	    glowstone_seeds = config.get(category, "glowstone_seeds", "ore:glowstone").getString();
	    gold_seeds = config.get(category, "gold_seeds", "ore:blockGold").getString();
	    grains_of_infinity_seeds = config.get(category, "grains_of_infinity_seeds", "ore:compressedx1DustBedrock").getString();
	    graphite_seeds = config.get(category, "graphite_seeds", "ore:blockGraphite").getString();
	    hop_graphite_seeds = config.get(category, "hop_graphite_seeds", "").getString();
	    ice_seeds = config.get(category, "ice_seeds", "").getString();
	    invar_seeds = config.get(category, "invar_seeds", "ore:blockInvar").getString();
	    iridium_ore_seeds = config.get(category, "iridium_ore_seeds", "ore:oreIridium").getString();
	    iridium_seeds = config.get(category, "iridium_seeds", "ore:blockIridium").getString();
	    iron_seeds = config.get(category, "iron_seeds", "ore:blockIron").getString();
	    ironwood_seeds = config.get(category, "ironwood_seeds", "twilightforest:block_storage").getString();
	    jade_seeds = config.get(category, "jade_seeds", "ore:blockJade").getString();
	    knightmetal_seeds = config.get(category, "knightmetal_seeds", "ore:blockKnightmetal").getString();
	    knightslime_seeds = config.get(category, "knightslime_seeds", "ore:blockKnightslime").getString();
	    lapis_lazuli_seeds = config.get(category, "lapis_lazuli_seeds", "ore:blockLapis").getString();
	    lead_seeds = config.get(category, "lead_seeds", "ore:blockLead").getString();
	    limestone_seeds = config.get(category, "limestone_seeds", "ore:stoneLimestone").getString();
	    lithium_seeds = config.get(category, "lithium_seeds", "ore:blockLithium").getString();
	    lumium_seeds = config.get(category, "lumium_seeds", "ore:blockLumium").getString();
	    magnesium_seeds = config.get(category, "magnesium_seeds", "ore:blockMagnesium").getString();
	    malachite_seeds = config.get(category, "malachite_seeds", "biomesoplenty:gem_block:5").getString();
	    manasteel_seeds = config.get(category, "manasteel_seeds", "botania:storage").getString();
	    manyullyn_seeds = config.get(category, "manyullyn_seeds", "ore:blockManyullyn").getString();
	    marble_seeds = config.get(category, "marble_seeds", "ore:stoneMarble").getString();
	    menril_seeds = config.get(category, "menril_seeds", "integrateddynamics:crystalized_menril_block").getString();
	    meteoric_iron_seeds = config.get(category, "meteoric_iron_seeds", "galacticraftcore:basic_block_core:12").getString();
	    mithril_seeds = config.get(category, "mithril_seeds", "ore:blockMithril").getString();
	    moonstone_seeds = config.get(category, "moonstone_seeds", "ore:blockMoonstone").getString();
	    mystical_flower_seeds = config.get(category, "mystical_flower_seeds", "botania:flower;botania:flower:1;botania:flower:2;botania:flower:3;botania:flower:4;botania:flower:5;botania:flower:6;botania:flower:7;botania:flower:8;botania:flower:9;botania:flower:10;botania:flower:11;botania:flower:12;botania:flower:13;botania:flower:14;botania:flower:15").getString();
	    nature_seeds = config.get(category, "nature_seeds", "").getString();
	    nether_quartz_seeds = config.get(category, "nether_quartz_seeds", "ore:blockQuartz").getString();
	    nether_seeds = config.get(category, "nether_seeds", "ore:netherrack").getString();
	    nickel_seeds = config.get(category, "nickel_seeds", "ore:blockNickel").getString();
	    obsidian_seeds = config.get(category, "obsidian_seeds", "ore:obsidian").getString();
	    octine_seeds = config.get(category, "octine_seeds", "ore:blockOctine").getString();
	    osmium_seeds = config.get(category, "osmium_seeds", "ore:blockOsmium").getString();
	    peridot_seeds = config.get(category, "peridot_seeds", "ore:blockPeridot").getString();
	    platinum_seeds = config.get(category, "platinum_seeds", "ore:blockPlatinum").getString();
	    pulsating_iron_seeds = config.get(category, "pulsating_iron_seeds", "ore:blockPulsatingIron").getString();
	    quartz_enriched_iron_seeds = config.get(category, "quartz_enriched_iron_seeds", "refinedstorage:quartz_enriched_iron_block").getString();
	    quicksilver_seeds = config.get(category, "quicksilver_seeds", "thaumcraft:ore_cinnabar").getString();
	    redstone_alloy_seeds = config.get(category, "redstone_alloy_seeds", "ore:blockRedstoneAlloy").getString();
	    redstone_seeds = config.get(category, "redstone_seeds", "ore:blockRedstone").getString();
	    refined_obsidian_seeds = config.get(category, "refined_obsidian_seeds", "ore:blockRefinedObsidian").getString();
	    rock_crystal_seeds = config.get(category, "rock_crystal_seeds", "astralsorcery:blockcustomore").getString();
	    rubber_seeds = config.get(category, "rubber_seeds", "ore:logRubber").getString();
	    ruby_seeds = config.get(category, "ruby_seeds", "ore:blockRuby").getString();
	    saltpeter_seeds = config.get(category, "saltpeter_seeds", "").getString();
	    sapphire_seeds = config.get(category, "sapphire_seeds", "ore:blockSapphire").getString();
	    signalum_seeds = config.get(category, "signalum_seeds", "ore:blockSignalum").getString();
	    silicon_seeds = config.get(category, "silicon_seeds", "ore:blockSilicon").getString();
	    silver_seeds = config.get(category, "silver_seeds", "ore:blockSilver").getString();
	    sky_stone_seeds = config.get(category, "sky_stone_seeds", "appliedenergistics2:sky_stone_block").getString();
	    slate_seeds = config.get(category, "slate_seeds", "ore:slate").getString();
	    slime_seeds = config.get(category, "slime_seeds", "ore:blockSlime;entity:minecraft:slime").getString();
	    slimy_bone_seeds = config.get(category, "slimy_bone_seeds", "ore:blockBone").getString();
	    soularium_seeds = config.get(category, "soularium_seeds", "ore:blockSoularium").getString();
	    star_steel_seeds = config.get(category, "star_steel_seeds", "ore:blockStarsteel").getString();
	    starmetal_seeds = config.get(category, "starmetal_seeds", "ore:oreAstralStarmetal").getString();
	    steel_seeds = config.get(category, "steel_seeds", "ore:blockSteel").getString();
	    steeleaf_seeds = config.get(category, "steeleaf_seeds", "ore:blockSteeleaf").getString();
	    stone_seeds = config.get(category, "stone_seeds", "ore:stone").getString();
	    sulfur_seeds = config.get(category, "sulfur_seeds", "").getString();
	    sunstone_seeds = config.get(category, "sunstone_seeds", "ore:blockSunstone").getString();
	    syrmorite_seeds = config.get(category, "syrmorite_seeds", "ore:blockSyrmorite").getString();
	    tanzanite_seeds = config.get(category, "tanzanite_seeds", "biomesoplenty:gem_block:4").getString();
	    terrasteel_seeds = config.get(category, "terrasteel_seeds", "botania:storage:1").getString();
	    thaumium_seeds = config.get(category, "thaumium_seeds", "ore:blockThaumium").getString();
	    thorium_seeds = config.get(category, "thorium_seeds", "ore:blockThroium").getString();
	    tin_seeds = config.get(category, "tin_seeds", "ore:blockTin").getString();
	    titanium_seeds = config.get(category, "titanium_seeds", "ore:blockTitanium").getString();
	    topaz_seeds = config.get(category, "topaz_seeds", "biomesoplenty:gem_block:3").getString();
	    tritanium_seeds = config.get(category, "tritanium_seeds", "ore:blockTritanium").getString();
	    tungsten_seeds = config.get(category, "tungsten_seeds", "ore:blockTungsten").getString();
	    uranium_238_seeds = config.get(category, "uranium_238_seeds", "ic2:resource:10").getString();
	    uranium_seeds = config.get(category, "uranium_seeds", "ore:blockUranium").getString();
	    valonite_seeds = config.get(category, "valonite_seeds", "ore:blockValonite").getString();
	    vibrant_alloy_seeds = config.get(category, "vibrant_alloy_seeds", "ore:blockVibrantAlloy").getString();
	    vinteum_seeds = config.get(category, "vinteum_seeds", "ore:blockVinteum").getString();
	    void_metal_seeds = config.get(category, "void_metal_seeds", "ore:blockVoid").getString();
	    water_seeds = config.get(category, "water_seeds", "minecraft:water").getString();
	    wood_seeds = config.get(category, "wood_seeds", "ore:logWood").getString();
	    yellorium_seeds = config.get(category, "yellorium_seeds", "ore:blockYellorium").getString();
	    zinc_seeds = config.get(category, "zinc_seeds", "ore:blockZinc").getString();
	    awakened_draconium_seeds = config.get(category, "awakened_draconium_seeds", "ore:blockDraconiumAwakened").getString();
	    dragon_egg_seeds = config.get(category, "dragon_egg_seeds", "minecraft:dragon_egg").getString();
	    nether_star_seeds = config.get(category, "nether_star_seeds", "ore:blockNetherStar").getString();
	    neutronium_seeds = config.get(category, "neutronium_seeds", "ore:blockCosmicNeutronium").getString();
		basalz_seeds = config.get(category, "basalz_seeds", "entity:thermalfoundation:basalz").getString();
		blaze_seeds = config.get(category, "blaze_seeds", "entity:minecraft:blaze").getString();
		blitz_seeds = config.get(category, "blitz_seeds", "entity:thermalfoundation:blitz").getString();
		blizz_seeds = config.get(category, "blizz_seeds", "entity:thermalfoundation:blizz").getString();
		chicken_seeds = config.get(category, "chicken_seeds", "entity:minecraft:chicken").getString();
		cow_seeds = config.get(category, "cow_seeds", "entity:minecraft:cow").getString();
		creeper_seeds = config.get(category, "creeper_seeds", "entity:minecraft:creeper").getString();
		enderman_seeds = config.get(category, "enderman_seeds", "entity:minecraft:enderman").getString();
		ghast_seeds = config.get(category, "ghast_seeds", "entity:minecraft:ghast").getString();
		guardian_seeds = config.get(category, "guardian_seeds", "entity:minecraft:guardian").getString();
		pig_seeds = config.get(category, "pig_seeds", "entity:minecraft:pig").getString();
		rabbit_seeds = config.get(category, "rabbit_seeds", "entity:minecraft:rabbit").getString();
		sheep_seeds = config.get(category, "sheep_seeds", "entity:minecraft:sheep").getString();
		skeleton_seeds = config.get(category, "skeleton_seeds", "entity:minecraft:skeleton").getString();
		spider_seeds = config.get(category, "spider_seeds", "entity:minecraft:spider").getString();
		wither_skeleton_seeds = config.get(category, "wither_skeleton_seeds", "entity:minecraft:wither_skeleton").getString();
		zombie_seeds = config.get(category, "zombie_seeds", "entity:minecraft:zombie").getString();
	    
		if(config.hasChanged()){
			config.save();
		}
	}
} 