modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Focamacho/MysticalAdaptations/issues"
license="MIT-1.0"
[[mods]]
modId="mysticaladaptations"
version="${file.jarVersion}"
displayName="Mystical Adaptations"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations"
credits="BlakeBr0 for Mystical Agriculture"
authors="focamacho"
description='''Insanium Armor, Insanium Tools and more.'''
[[dependencies.mysticaladaptations]]
    modId="mysticalagriculture"
    mandatory=true
    versionRange="[6,]"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.mysticaladaptations]]
    modId="mysticalagradditions"
    mandatory=true
    versionRange="[6,]"
    ordering="BEFORE"
    side="BOTH"